### PR TITLE
Blazing fast HTML escaping.

### PR DESCRIPTION
**Pull request by MrMage**
Resulting in 10x-100x (seriously) speedups across the board. And the common case where no replacements are needed actually benefits the most!

Screen Shot 2019-05-02 at 10 41 30
Screen Shot 2019-05-02 at 10 41 45

### CODE REVIEW

**Comment by MrMage** [comment]
This also yields a ~13% improvement in the old `LeafTests.testRenderPerformance()`:

Screen Shot 2019-05-02 at 10 56 15

**Comment by MrMage** [comment]
The remaining CI failure is unrelated to this PR, but we may want to only run these benchmarks in Release mode (they take much longer in Debug mode).

**Comment by MrMage** [comment]
Friendly ping @tanner0101 :-)

**Review by tanner0101 — APPROVED** [review]
Thanks, @MrMage ! 

I've opened an issue here to port these changes to LeafKit for Vapor 4: https://github.com/vapor/leaf-kit/issues/17

**Comment by penny-coin** [comment]
Hey @MrMage, you just merged a pull request, have a coin! 

You now have 29 coins.

**Pull request merged**
