### PR TITLE
Cache date formatters during a single template render operation.

### PR DESCRIPTION
**Pull request by MrMage**
Produces an extra 8% speedup in https://github.com/vapor/leaf/pull/137 on top of https://github.com/vapor/core/pull/199:

Screen Shot 2019-04-01 at 14 46 23

### CODE REVIEW

**Review by tanner0101 — APPROVED** [review]
We might be able to use a `NIO.ThreadSpecificVariable` here to get even better performance, but I think this is a good start at least.

**Comment by MrMage** [comment]
Yeah, I think creating one date formatter per render and per date format should be fine.

**Comment by MrMage** [comment]
Ist this ready to be merged?

**Review by tanner0101 — APPROVED** [review]
LGTM, thanks!

**Comment by penny-coin** [comment]
Hey @MrMage, you just merged a pull request, have a coin! 

You now have 27 coins.

**Pull request merged**
